### PR TITLE
Implement Add-Machine cmdlet

### PR DESCRIPTION
**Pull request by ryangribble**
Gday, 

Your octopus cmdlets look great!  I noticed Add-Machine was still in progress and had been disabled so I have finished off the coding for it.  Are you still working on this project?

PS I also found a problem with Add-Feed being defined as a duplicate Add-Environment which prevented the module from being imported in powershell, so ive also included a fix for that

Cheers

### CODE REVIEW

**Comment by ryangribble** [comment]
Build failed due to an unrelated failing test for CopyProject cmdlet, so ive fixed that up

Also I should mention that I had to change the TargetFramework to 4.5 because System.Management.Automation reference would not load when TargetFrameowkr was 4.0 (due to the Automation dll having a dependency on another system DLL that was targeting 4.5 after 4.5 installation.  Is targetting 4.5 OK?

**Comment by Swoogan** [comment]
Yes, I'm still working on the project when I have time. I'm not sure that targeting 4.5 will work. I think it might for users to run PowerShell 4 and I would like to keep the 2.0 requirement. However, I will review your commits and look into the framework version.

**Comment by ryangribble** [comment]
Yeah not sure about the framework, I couldn't get it to work targeting 4.0 due to  system.management.automation.dll referencing something else which was now 4.5

Great that you are still working on this, I will submit some more contributions like getting the current versions deployed (through the dashboard  API objects) and things like that

**Comment by Swoogan** [comment]
Ryan,

Were you building on Windows 10? I just upgraded and now I'm getting an error about System.Management.Automation because it's dependency is build against .NET 4.5.

**Comment by ryangribble** [comment]
Yeah I was on windows 10

**Pull request merged**
