### PR TITLE
Updated proxy libs, .NET Core project system, Copy-OctoChannel

### PR DESCRIPTION
**Pull request by vojtechvit**
1. Solution converted to .NET Core project system.
2. Octopus proxy libs updated to latest version.
3. ```Copy-OctoChannel``` CmdLet added.

### CODE REVIEW

**Comment by vojtechvit** [comment]
Hi @Swoogan @ryangribble,

Do you have time to take a look at this PR? :-) It adds some CmdLets we need and it updates Octopus libs, consequently fixing some existing CmdLets to work with recent versions of Octopus - e.g. ```Copy-OctoProject``` crashes when I try to copy one of our projects with the current codebase.

If you can, please check whether the PR quality is good enough and consider adding me to contributors so I can make further updates over time. I love your library's quality and ease of use and it would be a shame to leave it outdated! ;-)

Cheers!

**Comment by Swoogan** [comment]
I did a quick review and it looks good. I just need to test it locally. One question I have is whether the porting to .NET Core means that it will not longer work with the older frameworks like 4.5-4.7?

**Comment by Swoogan** [comment]
Or perhaps a better question is, what does updating to .NET Core mean in terms of PowerShell version targeting? I've attempted to target a lowest common denominator for PowerShell versions.

**Comment by ryangribble** [comment]
It looks to me that it's just updating the project format/build system to the vs2017 dotnetcore csproj format and build tooling, but still using a target framework of net45 (except the test project which is net461 for some reason?) so it's actually still just a 4.5 full framework library

**Comment by vojtechvit** [comment]
@Swoogan it still targets net45 as before as can be seen [here|https://github.com/Swoogan/Octopus-Cmdlets/pull/10/files#diff-909a6bc574ea4c1518a7354d9109ff53R4] - i.e. it doesn't target .NET Core nor .NET Standard atm. The change is only in the tooling.

**Comment by vojtechvit** [comment]
@ryangribble correct. The test project targets net461 to allow newer testing tools to be used in case they require newer framework versions.

**Comment by vojtechvit** [comment]
By the way once Microsoft finishes PowerShell 6 Core, it will be relatively easy to target .NET Standard and consequently make this module usable on Windows, MacOS and Linux. Also developers running those platforms will be able to open the solution and compile it.

**Pull request merged**
